# **Numpy**

Numpy merupakan sebuah library python yang open-source yang digunakan hampir setiap bidang sains dan teknik. Numpy pada python berfungsi untuk melakukan operasi vektor dan matriks dengan mengelola array serta array multi dimensi.

### **Installing Numpy**

Jika telah menginstall python maka dapat menggunakan syntax :

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### **Import numpy**

In [2]:
import numpy as np #Syntax untuk import numpy

## **Array**

Array pada python dapat digunakan di dalam library Numpy. Berbeda dengan list karena array memiliki tipe data yang sama list dapat berisi tipe data yang berbeda, semua elemen dalam array harus homogen.

Contoh penggunaan array :

Untuk membuat Numpy Array, Syntax yang digunakan : 
- np.array()
- np.zeros()
- np.ones()
- np.empty()
- np.arange()

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8]]) #Terdapat 2 tambahan square bracket maka array akan membentuk 2Dimensi
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
np.zeros(2)

array([0., 0.])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.empty(3) #Empty array akan mengambil isi dari memory terakhir

array([1., 1., 1.])

In [7]:
print(np.arange(3))
print(np.arange(0,10,2)) #([Start] , [Stop], [Step]) 

[0 1 2]
[0 2 4 6 8]


## **Add, Remove and Sort**

Untuk menambah array dapat menggunakan syntax : np.append(nama_array,Nilai tambahan)

In [8]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
np.append(a, [5,6])

array([1, 2, 3, 4, 5, 6])

Untuk mendelete array dapat menggunakan syntax : np.delete().
Sebagai contoh jika ingin mendelete elemen pada posisi 1 :


In [10]:
np.delete(a,1)

array([1, 3, 4])

Untuk mengurutkan elemen dapat menggunakan syntax : np.sort()

In [11]:
a = np.array([3,4,1,6,7,9,10])
print(a)

[ 3  4  1  6  7  9 10]


In [12]:
np.sort(a)

array([ 1,  3,  4,  6,  7,  9, 10])

## **Shape and Size**

- array_name.ndim
- array_name.size
- array_name.shape

ndim berfungsi untuk memberi tahu jumlah dimensi dari sebuah array.

size berfungsi memberi tahu jumlah total elemen dari sebuah array.

shape berfungsi untuk menunjukkan jumlah elemen yang disimpan pada dimensi array. Sebagai contoh jika memiliki array 2D dengan 2 baris dan 3 kolom maka shape dari array tersebut (2,3)

In [13]:
arr = np.array([[1,2,3,4] , [5,6,7,8],
               [0,1,2,3,] , [4,5,6,7]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [0 1 2 3]
 [4 5 6 7]]


In [14]:
arr.ndim

2

In [15]:
arr.size

16

In [16]:
arr.shape

(4, 4)

## **Reshape**

Menggunakan reshape akan memberikan bentuk baru array tanpa merubah apapun tetapi perlu diingat, ketika menggunakan metode reshape array yang ingin dihasilkan harus memiliki jumlah elemen yang sama dengan array yang asli.
Contoh:

In [17]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [18]:
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


## **Convert 1D to 2D**

- np.newaxis
- np expand_dims

Menggunakan array_name.newaxis akan meningkatkan dimensi sebuah array. Dimana array 1D akan menjadi 2D, array 2D akan menjadi 4D dst..

contoh :

In [19]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [20]:
a2 = a[np.newaxis]
a2.shape


(1, 6)

In [21]:
#Mengconvert array 1D menjadi vektor baris

row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [22]:
#Mengconvert array 1D menjadi vektor kolom

col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [23]:
print(col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Memperluas array juga dapat dilakukan dengan memasukkan newaxis pada posisi yang ditentukan dengan np.expand_dims. Contoh

In [24]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [25]:
b = np.expand_dims(a, axis = 1)
b.shape

(6, 1)

In [26]:
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [27]:
c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

In [28]:
print(c)

[[1 2 3 4 5 6]]


## **Indexing & Slicing**

Penggunaan indexing & Slicing pada NumPy array sama seperti pada python List

In [29]:
data = np.array([1,2,3])

print(data[0])
print(data[1])
print(data[1:])
print(data[0:2])

1
2
[2 3]
[1 2]


Jika ingin memilih nilai dari array dan ingin memenuhi persyaratan terntu seperti operasi aritmatika, lebih mudah dengan NumPy. Contoh :

In [30]:
a = np.array([[1,2,3,4] , [5,6,7,8] , [9,10,11,12]])

In [31]:
print(a[a<5])

[1 2 3 4]


In [32]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [33]:
HabisDibagi2 = a[a%2==0]
print(HabisDibagi2)

[ 2  4  6  8 10 12]


In [34]:
#Dapat juga memilih elemen dengan 2 kondisi menggunakan & dan / operators
c = a[(a>2) & (a<8)]
print(c)

[3 4 5 6 7]


## **Creating Array From Existing Data**

Membuat array baru dari bagian array yang sudah ada. Contoh :

In [35]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

Kita dapat membuat array baru dari bagian diatas kapan saja dengan menentukan slice dari array tersebut.

In [36]:
a2 = a[3:8]
a2

array([4, 5, 6, 7, 8])

Kita juga dapat menumpuk 2 array yang ada, baik secara vertikal maupun horizontal. Contoh :

In [37]:
a_1 = np.array([[1,1],
               [2,2]])
print(a_1)

[[1 1]
 [2 2]]


In [38]:
a_2 = np.array([[3,3],
               [4,4]])
print(a_2)

[[3 3]
 [4 4]]


In [39]:
#Menggunakan vstack jika ingin secara vertikal
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [40]:
#Menggunakan hstack jika ingin secara horizontal
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

Membuat array menjadi beberapa array yang lebih kecil dengan menggunakan hsplit dan dapat menentukan jumlah array yang ingin dibentuk.

In [41]:
arrsplit = np.arange(15)

In [42]:
np.hsplit(arrsplit,5)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14])]

## **Operasi pada Array**

In [43]:
#Sum Operations untuk mengjumlah semua elemen di dalam array

a = np.array([1,2,3,4])

a.sum()

10

Untuk mejumlah baris dan kolom pada array 2D menggunakan axis 0 untuk baris dan 1 untuk kolom.

In [44]:
b = np.array([[1,1]
             ,[2,2]])

In [45]:
#Contoh untuk menjumlah baris pada array 2D

b.sum(axis=0)

array([3, 3])

In [46]:
#Menjumlah kolom pada array 2D
b.sum(axis=1)

array([2, 4])

## **Broadcasting**

Operasi antara vektor dan skalar atau antara array dari ukuran yang berbeda. contoh :

In [47]:
print(b)

[[1 1]
 [2 2]]


In [48]:
b * 2

array([[2, 2],
       [4, 4]])

## **More Array Operations**

- data.max()
- data.min()
- data.sum()

In [49]:
a3 = np.random.rand(6)
print(a3)

[0.32291311 0.58312666 0.75252149 0.16210782 0.48950784 0.26966228]


In [50]:
a3.sum()

2.579839204905165

In [51]:
a3.max()

0.752521494807952

In [52]:
a3.min()

0.1621078230066475

## **Matrices Arithmatic**

Menambah dan Mengalikan matriks menggunakan operator aritmatika, jika kedua matriks tersebut berukuran sama.

In [53]:
data = np.array([[1,2],
                 [3,4]])
print(data)

[[1 2]
 [3 4]]


In [54]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [55]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


## **Dot Products**

Dot products digunakan untuk kasus perkalian pada matriks. Contoh :

In [56]:
a_1 = np.array([[1,2,3],
               [3,3,4]])
print(a_1)

[[1 2 3]
 [3 3 4]]


In [57]:
a_2 = np.array([[1,3],
               [2,4],
               [3,5]])
print(a_2)

[[1 3]
 [2 4]
 [3 5]]


In [58]:
np.dot(a_1,a_2)

array([[14, 26],
       [21, 41]])

## **Matrix Indexing**

In [59]:
data = np.array([[1,2] , [3,4] , [5,6]])
print(data)
print(data[0:1])
print(data[1:3])

[[1 2]
 [3 4]
 [5 6]]
[[1 2]]
[[3 4]
 [5 6]]


## **Matrix Agregation**

Menggabungkan matrix dengan cara mengumpulkan vektor.

In [60]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [61]:
print(data.max())

6


In [62]:
print(data.min())

1


In [63]:
print(data.sum(axis=0))

[ 9 12]


In [64]:
print(data.sum(axis=1))

[ 3  7 11]


### Transpose & Reshape

Transpose untuk mengubah baris menjadi kolom atau sebaliknya.

In [65]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [66]:
print(data.T) #--> Syntax untuk mentranspose matriks

[[1 3 5]
 [2 4 6]]


In [67]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [68]:
arr.reshape(2,3) #--> Syntax untuk reshape matriks

array([[0, 1, 2],
       [3, 4, 5]])

## **Flatten N-Dimension Array**

ada 2 cara untuk meratakan sebuah array dengan .flatten() dan ravel().

In [4]:
arrflat = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(arrflat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [5]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## **Notes on Numpy Array**

In [7]:
a = np.random.rand(5) #Rank 1 array / skalar

In [8]:
print(a)

[0.85980207 0.59739652 0.77299744 0.6204474  0.67233625]


In [9]:
a.shape

(5,)

In [10]:
print(np.dot(a,a.T))

2.5306582435207554


In [11]:
a = np.random.rand(5,1) #Dengan colum vektor

In [12]:
print(a)

[[0.28891497]
 [0.16043711]
 [0.86169427]
 [0.03473321]
 [0.71024932]]


In [13]:
print(np.dot(a,a.T))

[[0.08347186 0.04635268 0.24895638 0.01003494 0.20520166]
 [0.04635268 0.02574007 0.13824774 0.0055725  0.11395035]
 [0.24895638 0.13824774 0.74251702 0.02992941 0.61201777]
 [0.01003494 0.0055725  0.02992941 0.0012064  0.02466924]
 [0.20520166 0.11395035 0.61201777 0.02466924 0.50445409]]


Jangan menggunakan rank 1 array, selalu gunakan matriks 1x1 ataupun matrik yang lainnya.